const fs = require('fs')
var driver = [
    {
        name: 'Mario',
        size: 'Medium',
        driverModel: 'MediumDriverModel4'
    },
    {
        name: 'Luigi',
        size: 'Medium',
        driverModel: 'MediumDriverModel3'
    },
    {
        name: 'Peach',
        size: 'Medium',
        driverModel: 'MediumDriverModel1'
    },
    {
        name: 'Daisy',
        size: 'Medium',
        driverModel: 'MediumDriverModel1'
    },
    {
        name: 'Rosalina',
        size: 'Large',
        driverModel: 'HeavyDriverModel0'
    },
    {
        name: 'Tanooki Mario',
        size: 'Medium',
        driverModel: 'MediumDriverModel2'
    },
    {
        name: 'Cat Peach',
        size: 'Medium',
        driverModel: 'MediumDriverModel0'
    },
    {
        name: 'Yoshi',
        size: 'Medium',
        driverModel: 'MediumDriverModel1'
    },
    {
        name: 'Toad',
        size: 'Small',
        driverModel: 'LightDriverModel5'
    },
    {
        name: 'Koopa Troopa',
        size: 'Small',
        driverModel: 'LightDriverModel3'
    },
    {
        name: 'Shy Guy',
        size: 'Small',
        driverModel: 'LightDriverModel5'
    },
    {
        name: 'Lakitu',
        size: 'Small',
        driverModel: 'LightDriverModel3'
    },
    {
        name: 'Toadette',
        size: 'Small',
        driverModel: 'LightDriverModel4'
    },
    {
        name: 'King Boo',
        size: 'Large',
        driverModel: 'HeavyDriverModel0'
    },
    {
        name: 'Baby Mario',
        size: 'Small',
        driverModel: 'LightDriverModel2'
    },
    {
        name: 'Baby Luigi',
        size: 'Small',
        driverModel: 'LightDriverModel2'
    },
    {
        name: 'Baby Peach',
        size: 'Small',
        driverModel: 'LightDriverModel0'
    },
    {
        name: 'Baby Daisy',
        size: 'Small',
        driverModel: 'LightDriverModel0'
    },
    {
        name: 'Baby Rosalina',
        size: 'Small',
        driverModel: 'LightDriverModel1'
    },
    {
        name: 'Metal Mario',
        size: 'Medium',
        driverModel: 'HeavyDriverModel3'
    },
    {
        name: 'Pink Gold Peach',
        size: 'Medium',
        driverModel: 'HeavyDriverModel3'
    },
    {
        name: 'Wario',
        size: 'Large',
        driverModel: 'HeavyDriverModel2'
    },
    {
        name: 'Waluigi',
        size: 'Large',
        driverModel: 'HeavyDriverModel1'
    },
    {
        name: 'Donkey Kong',
        size: 'Large',
        driverModel: 'HeavyDriverModel1'
    },
    {
        name: 'Bowser',
        size: 'Large',
        driverModel: 'HeavyDriverModel4'
    },
    {
        name: 'Dry Bones',
        size: 'Small',
        driverModel: 'LightDriverModel2'
    },
    {
        name: 'Bowser Jr',
        size: 'Small',
        driverModel: 'LightDriverModel3'
    },
    {
        name: 'Dry Bowser',
        size: 'Large',
        driverModel: 'HeavyDriverModel2'
    },
    {
        name: 'Lemmy',
        size: 'Small',
        driverModel: 'LightDriverModel1'
    },
    {
        name: 'Larry',
        size: 'Small',
        driverModel: 'LightDriverModel5'
    },
    {
        name: 'Wendy',
        size: 'Small',
        driverModel: 'LightDriverModel4'
    },
    {
        name: 'Ludwig',
        size: 'Medium',
        driverModel: 'MediumDriverModel4'
    },
    {
        name: 'Iggy',
        size: 'Medium',
        driverModel: 'MediumDriverModel3'
    },
    {
        name: 'Roy',
        size: 'Large',
        driverModel: 'HeavyDriverModel1'
    },
    {
        name: 'Morton',
        size: 'Large',
        driverModel: 'HeavyDriverModel4'
    },
    {
        name: 'Inkling Girl',
        size: 'Medium',
        driverModel: 'MediumDriverModel0'
    },
    {
        name: 'Inkling Boy',
        size: 'Medium',
        driverModel: 'MediumDriverModel2'
    },
    {
        name: 'Link',
        size: 'Large',
        driverModel: 'HeavyDriverModel0'
    },
    {
        name: 'Villager (male)',
        size: 'Medium',
        driverModel: 'MediumDriverModel2'
    },
    {
        name: 'Villager (female)',
        size: 'Medium',
        driverModel: 'MediumDriverModel0'
    },
    {
        name: 'Isabelle',
        size: 'Small',
        driverModel: 'LightDriverModel4'
    },
    {
        name: 'Mii (Light)',
        size: 'Small',
        driverModel: 'LightDriverModel2'
    },
    {
        name: 'Mii (Medium)',
        size: 'Medium',
        driverModel: 'MediumDriverModel4'
    },
    {
        name: 'Mii (Heavy)',
        size: 'Large',
        driverModel: 'HeavyDriverModel4'
    }
];

var driverModel = [
    {
        name: 'LightDriverModel0',
        size: '',
        speedGnd: 2.25,
        speedWtr: 2.5,
        speedAir: 2.75,
        speedGty: 2,
        acceleration: 4,
        weight: 2,
        handlingGnd: 5,
        handlingWtr: 4.5,
        handlingAir: 5,
        handlingGty: 5,
        grip: 4.25,
        miniturbo: 4,
        active: false
    },
    {
        name: 'LightDriverModel1',
        size: '',
        speedGnd: 2.25,
        speedWtr: 2.5,
        speedAir: 2.75,
        speedGty: 2,
        acceleration: 4.25,
        weight: 2,
        handlingGnd: 4.75,
        handlingWtr: 4.25,
        handlingAir: 4.75,
        handlingGty: 4.75,
        grip: 3.75,
        miniturbo: 4,
        active: false
    },
    {
        name: 'LightDriverModel2',
        size: '',
        speedGnd: 2.5,
        speedWtr: 2.75,
        speedAir: 3,
        speedGty: 2.25,
        acceleration: 4.25,
        weight: 2.25,
        handlingGnd: 4.5,
        handlingWtr: 4,
        handlingAir: 4.5,
        handlingGty: 4.5,
        grip: 4,
        miniturbo: 3.75,
        active: false
    },
    {
        name: 'LightDriverModel3',
        size: '',
        speedGnd: 2.75,
        speedWtr: 3,
        speedAir: 3.25,
        speedGty: 2.5,
        acceleration: 4,
        weight: 2.5,
        handlingGnd: 4.5,
        handlingWtr: 4,
        handlingAir: 4.5,
        handlingGty: 4.5,
        grip: 4.25,
        miniturbo: 3.75,
        active: false
    },
    {
        name: 'LightDriverModel4',
        size: '',
        speedGnd: 2.75,
        speedWtr: 3,
        speedAir: 3.25,
        speedGty: 2.5,
        acceleration: 4.25,
        weight: 2.5,
        handlingGnd: 4.25,
        handlingWtr: 3.75,
        handlingAir: 4.25,
        handlingGty: 4.25,
        grip: 3.5,
        miniturbo: 3.75,
        active: false
    },
    {
        name: 'LightDriverModel5',
        size: '',
        speedGnd: 3,
        speedWtr: 3.25,
        speedAir: 3.5,
        speedGty: 2.75,
        acceleration: 4,
        weight: 2.75,
        handlingGnd: 4.25,
        handlingWtr: 3.75,
        handlingAir: 4.25,
        handlingGty: 4.25,
        grip: 4,
        miniturbo: 3.5,
        active: false
    },
    {
        name: 'MediumDriverModel0',
        size: '',
        speedGnd: 3.25,
        speedWtr: 3.5,
        speedAir: 3.75,
        speedGty: 3,
        acceleration: 4,
        weight: 2.75,
        handlingGnd: 4,
        handlingWtr: 3.5,
        handlingAir: 4,
        handlingGty: 4,
        grip: 3.75,
        miniturbo: 3.5,
        active: false
    },
    {
        name: 'MediumDriverModel1',
        size: '',
        speedGnd: 3.5,
        speedWtr: 3.75,
        speedAir: 4,
        speedGty: 3.25,
        acceleration: 3.75,
        weight: 3,
        handlingGnd: 3.75,
        handlingWtr: 3.25,
        handlingAir: 3.75,
        handlingGty: 3.75,
        grip: 3.75,
        miniturbo: 3.5,
        active: false
    },
    {
        name: 'MediumDriverModel2',
        size: '',
        speedGnd: 3.5,
        speedWtr: 3.75,
        speedAir: 4,
        speedGty: 3.25,
        acceleration: 3.75,
        weight: 3.25,
        handlingGnd: 3.75,
        handlingWtr: 3.25,
        handlingAir: 3.75,
        handlingGty: 3.75,
        grip: 3.25,
        miniturbo: 3.5,
        active: false
    },
    {
        name: 'MediumDriverModel3',
        size: '',
        speedGnd: 3.75,
        speedWtr: 4,
        speedAir: 4.25,
        speedGty: 3.5,
        acceleration: 3.5,
        weight: 3.5,
        handlingGnd: 3.75,
        handlingWtr: 3.25,
        handlingAir: 3.75,
        handlingGty: 3.75,
        grip: 3.25,
        miniturbo: 3.25,
		active: false
    },
    {
        name: 'MediumDriverModel4',
        size: '',
        speedGnd: 3.75,
        speedWtr: 4,
        speedAir: 4.25,
        speedGty: 3.5,
        acceleration: 3.5,
        weight: 3.5,
        handlingGnd: 3.5,
        handlingWtr: 3,
        handlingAir: 3.5,
        handlingGty: 3.5,
        grip: 3.5,
        miniturbo: 3.25,
		active: false
    },
    {
        name: 'HeavyDriverModel0',
        size: '',
        speedGnd: 4,
        speedWtr: 4.25,
        speedAir: 4.5,
        speedGty: 3.75,
        acceleration: 3.25,
        weight: 3.75,
        handlingGnd: 3.25,
        handlingWtr: 2.75,
        handlingAir: 3.25,
        handlingGty: 3.25,
        grip: 3.75,
        miniturbo: 3.25,
		active: false
    },
    {
        name: 'HeavyDriverModel1',
        size: '',
        speedGnd: 4.5,
        speedWtr: 4.75,
        speedAir: 5,
        speedGty: 4.25,
        acceleration: 3.25,
        weight: 4,
        handlingGnd: 3,
        handlingWtr: 2.5,
        handlingAir: 3,
        handlingGty: 3,
        grip: 3,
        miniturbo: 3,
        active: false
    },
    {
        name: 'HeavyDriverModel2',
        size: '',
        speedGnd: 4.75,
        speedWtr: 5,
        speedAir: 5.25,
        speedGty: 4.5,
        acceleration: 3,
        weight: 4.25,
        handlingGnd: 2.75,
        handlingWtr: 2.25,
        handlingAir: 2.75,
        handlingGty: 2.75,
        grip: 3.25,
        miniturbo: 2.75,
        active: false
    },
    {
        name: 'HeavyDriverModel3',
        size: '',
        speedGnd: 4.25,
        speedWtr: 4.5,
        speedAir: 4.75,
        speedGty: 4,
        acceleration: 3.25,
        weight: 4.5,
        handlingGnd: 3.25,
        handlingWtr: 2.75,
        handlingAir: 3.25,
        handlingGty: 3.25,
        grip: 3.25,
        miniturbo: 3,
        active: false
    },
    {
        name: 'HeavyDriverModel4',
        size: '',
        speedGnd: 4.75,
        speedWtr: 5,
        speedAir: 5.25,
        speedGty: 4.5,
        acceleration: 3,
        weight: 4.5,
        handlingGnd: 2.5,
        handlingWtr: 2,
        handlingAir: 2.5,
        handlingGty: 2.5,
        grip: 3,
        miniturbo: 2.75,
        active: false
    }
];

var body = [
    {
        name: 'Pipe Frame',
        speedGnd: -0.5,
        speedWtr: 0,
        speedAir: -0.5,
        speedGty: -0.5,
        acceleration: 0.5,
        weight: -0.25,
        handlingGnd: 0.5,
        handlingWtr: 0.5,
        handlingAir: -0.25,
        handlingGty: 0.25,
        grip: 0.25,
        miniturbo: 0.5
    },
    {
        name: 'Mach 8',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0.25,
        speedGty: 0.5,
        acceleration: -0.25,
        weight: 0.25,
        handlingGnd: -0.25,
        handlingWtr: 0,
        handlingAir: -0.25,
        handlingGty: 0.25,
        grip: 0.25,
        miniturbo: 0
    },
    {
        name: 'Steel Driver',
        speedGnd: 0.25,
        speedWtr: 0.5,
        speedAir: -0.75,
        speedGty: -0.25,
        acceleration: -0.75,
        weight: 0.5,
        handlingGnd: -0.5,
        handlingWtr: 0.75,
        handlingAir: -0.5,
        handlingGty: -0.5,
        grip: 0,
        miniturbo: -0.5
    },
    {
        name: 'Cat Cruiser',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: 0.25,
        speedGty: 0,
        acceleration: 0.25,
        weight: 0,
        handlingGnd: 0.25,
        handlingWtr: 0,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0.25
    },
    {
        name: 'Circuit Special',
        speedGnd: 0.5,
        speedWtr: -0.5,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: -0.75,
        weight: 0.25,
        handlingGnd: -0.5,
        handlingWtr: -0.25,
        handlingAir: -0.75,
        handlingGty: -0.25,
        grip: -0.5,
        miniturbo: -0.75
    },
    {
        name: 'Tri-Speeder',
        speedGnd: 0.25,
        speedWtr: 0.5,
        speedAir: -0.75,
        speedGty: -0.25,
        acceleration: -0.75,
        weight: 0.5,
        handlingGnd: -0.5,
        handlingWtr: 0.75,
        handlingAir: -0.5,
        handlingGty: -0.5,
        grip: 0,
        miniturbo: -0.5
    },
    {
        name: 'Badwagon',
        speedGnd: 0.5,
        speedWtr: -0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -1,
        weight: 0.5,
        handlingGnd: -0.75,
        handlingWtr: -0.25,
        handlingAir: -0.75,
        handlingGty: -0.5,
        grip: 0.5,
        miniturbo: -1
    },
    {
        name: 'Prancer',
        speedGnd: 0.25,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: -0.5,
        weight: -0.25,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: -0.25
    },
    {
        name: 'Biddybuggy',
        speedGnd: -0.75,
        speedWtr: -0.5,
        speedAir: -0.5,
        speedGty: -0.25,
        acceleration: 0.75,
        weight: -0.5,
        handlingGnd: 0.5,
        handlingWtr: 0.5,
        handlingAir: 0.25,
        handlingGty: 0.5,
        grip: 0.25,
        miniturbo: 0.75
    },
    {
        name: 'Landship',
        speedGnd: -0.5,
        speedWtr: 0.5,
        speedAir: -0.25,
        speedGty: -0.75,
        acceleration: 0.5,
        weight: -0.5,
        handlingGnd: 0.25,
        handlingWtr: 0.75,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: 0.75,
        miniturbo: 0.5
    },
    {
        name: 'Sneeker',
        speedGnd: 0.25,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0,
        acceleration: -0.5,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: -0.25,
        handlingGty: 0,
        grip: -0.75,
        miniturbo: -0.25
    },
    {
        name: 'Sports Coupe',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0.25,
        speedGty: 0.5,
        acceleration: -0.25,
        weight: 0.25,
        handlingGnd: -0.25,
        handlingWtr: 0,
        handlingAir: -0.25,
        handlingGty: 0.25,
        grip: 0.25,
        miniturbo: 0
    },
    {
        name: 'Gold Standard',
        speedGnd: 0.25,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0,
        acceleration: -0.5,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: -0.25,
        handlingGty: 0,
        grip: -0.75,
        miniturbo: -0.25
    },
    {
        name: 'GLA',
        speedGnd: 0.5,
        speedWtr: -0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -1,
        weight: 0.5,
        handlingGnd: -0.75,
        handlingWtr: -0.25,
        handlingAir: -0.75,
        handlingGty: -0.5,
        grip: 0.5,
        miniturbo: -1
    },
    {
        name: 'W 25 Silver Arrow',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: -0.25,
        handlingGnd: 0.25,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: 0.25,
        grip: 0.5,
        miniturbo: 0.25
    },
    {
        name: '300 SL Roadster',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0
    },
    {
        name: 'Blue Falcon',
        speedGnd: 0.25,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0.25,
        acceleration: -0.25,
        weight: -0.5,
        handlingGnd: -0.25,
        handlingWtr: 0.25,
        handlingAir: -0.5,
        handlingGty: 0.5,
        grip: 0,
        miniturbo: -0.25
    },
    {
        name: 'Tanooki Kart',
        speedGnd: -0.25,
        speedWtr: 0.25,
        speedAir: 0,
        speedGty: 0,
        acceleration: -0.5,
        weight: 0.25,
        handlingGnd: 0.25,
        handlingWtr: 0.5,
        handlingAir: 0,
        handlingGty: 0,
        grip: 1,
        miniturbo: -0.25
    },
    {
        name: 'B Dasher',
        speedGnd: 0.5,
        speedWtr: -0.5,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: -0.75,
        weight: 0.25,
        handlingGnd: -0.5,
        handlingWtr: -0.25,
        handlingAir: -0.75,
        handlingGty: -0.25,
        grip: -0.5,
        miniturbo: -0.75
    },
    {
        name: 'Streetle',
        speedGnd: -0.5,
        speedWtr: 0.5,
        speedAir: -0.25,
        speedGty: -0.75,
        acceleration: 0.5,
        weight: -0.5,
        handlingGnd: 0.25,
        handlingWtr: 0.75,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: 0.75,
        miniturbo: 0.5
    },
    {
        name: 'P-Wing',
        speedGnd: 0.5,
        speedWtr: -0.5,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: -0.75,
        weight: 0.25,
        handlingGnd: -0.5,
        handlingWtr: -0.25,
        handlingAir: -0.75,
        handlingGty: -0.25,
        grip: -0.5,
        miniturbo: -0.75
    },
    {
        name: 'Koopa Clown',
        speedGnd: -0.25,
        speedWtr: 0.25,
        speedAir: 0,
        speedGty: 0,
        acceleration: -0.5,
        weight: 0.25,
        handlingGnd: 0.25,
        handlingWtr: 0.5,
        handlingAir: 0,
        handlingGty: 0,
        grip: 1,
        miniturbo: -0.25
    },
    {
        name: 'Standard Bike',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: -0.25,
        handlingGnd: 0.25,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: 0.25,
        grip: 0.5,
        miniturbo: 0.25
    },
    {
        name: 'Comet',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: 0.25,
        speedGty: 0,
        acceleration: 0.25,
        weight: 0,
        handlingGnd: 0.25,
        handlingWtr: 0,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0.25,
        insideDrift: true
    },
    {
        name: 'Sport Bike',
        speedGnd: 0.25,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: -0.5,
        weight: -0.25,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: -0.25,
        insideDrift: true
    },
    {
        name: 'The Duke',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0
    },
    {
        name: 'Flame Rider',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: -0.25,
        handlingGnd: 0.25,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: 0.25,
        grip: 0.5,
        miniturbo: 0.25
    },
    {
        name: 'Varmint',
        speedGnd: -0.5,
        speedWtr: 0,
        speedAir: -0.5,
        speedGty: -0.5,
        acceleration: 0.5,
        weight: -0.25,
        handlingGnd: 0.5,
        handlingWtr: 0.5,
        handlingAir: -0.25,
        handlingGty: 0.25,
        grip: 0.25,
        miniturbo: 0.5
    },
    {
        name: 'Mr Scooty',
        speedGnd: -0.75,
        speedWtr: -0.5,
        speedAir: -0.5,
        speedGty: -0.25,
        acceleration: 0.75,
        weight: -0.5,
        handlingGnd: 0.5,
        handlingWtr: 0.5,
        handlingAir: 0.25,
        handlingGty: 0.5,
        grip: 0.25,
        miniturbo: 0.75
    },
    {
        name: 'Jet Bike',
        speedGnd: 0.25,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: -0.5,
        weight: -0.25,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: -0.25,
        insideDrift: true
    },
    {
        name: 'Yoshi Bike',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: 0.25,
        speedGty: 0,
        acceleration: 0.25,
        weight: 0,
        handlingGnd: 0.25,
        handlingWtr: 0,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0.25,
        insideDrift: true
    },
    {
        name: 'Master Cycle',
        speedGnd: 0.25,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0,
        acceleration: -0.5,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: -0.25,
        handlingGty: 0,
        grip: -0.75,
        miniturbo: -0.25,
        insideDrift: true
    },
    {
        name: 'Master Cycle Zero',
        speedGnd: -0.25,
        speedWtr: 0.25,
        speedAir: 0,
        speedGty: 0,
        acceleration: -0.5,
        weight: 0.25,
        handlingGnd: 0.25,
        handlingWtr: 0.5,
        handlingAir: 0,
        handlingGty: 0,
        grip: 1,
        miniturbo: -0.25
    },
    {
        name: 'City Tripper',
        speedGnd: -0.5,
        speedWtr: 0,
        speedAir: -0.5,
        speedGty: -0.5,
        acceleration: 0.5,
        weight: -0.25,
        handlingGnd: 0.5,
        handlingWtr: 0.5,
        handlingAir: -0.25,
        handlingGty: 0.25,
        grip: 0.25,
        miniturbo: 0.5
    },
    {
        name: 'Standard ATV',
        speedGnd: 0.5,
        speedWtr: -0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -1,
        weight: 0.5,
        handlingGnd: -0.75,
        handlingWtr: -0.25,
        handlingAir: -0.75,
        handlingGty: -0.5,
        grip: 0.5,
        miniturbo: -1
    },
    {
        name: 'Wild Wiggler',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: -0.25,
        handlingGnd: 0.25,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: 0.25,
        grip: 0.5,
        miniturbo: 0.25
    },
    {
        name: 'Teddy Buggy',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: 0.25,
        speedGty: 0,
        acceleration: 0.25,
        weight: 0,
        handlingGnd: 0.25,
        handlingWtr: 0,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0.25
    },
    {
        name: 'Bone Rattler',
        speedGnd: 0.25,
        speedWtr: 0.5,
        speedAir: -0.75,
        speedGty: -0.25,
        acceleration: -0.75,
        weight: 0.5,
        handlingGnd: -0.5,
        handlingWtr: 0.75,
        handlingAir: -0.5,
        handlingGty: -0.5,
        grip: 0,
        miniturbo: -0.5
    },
    {
        name: 'Splat Buggy',
        speedGnd: 0.25,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0.25,
        acceleration: -0.25,
        weight: -0.5,
        handlingGnd: -0.25,
        handlingWtr: 0.25,
        handlingAir: -0.5,
        handlingGty: 0.5,
        grip: 0,
        miniturbo: -0.25
    },
    {
        name: 'Inkstriker',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0.25,
        speedGty: 0.5,
        acceleration: -0.25,
        weight: 0.25,
        handlingGnd: -0.25,
        handlingWtr: 0,
        handlingAir: -0.25,
        handlingGty: 0.25,
        grip: 0.25,
        miniturbo: 0
    }
];

var tire = [
    {
        name: 'Standard',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0
    },
    {
        name: 'Monster',
        speedGnd: 0,
        speedWtr: -0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -0.5,
        weight: 0.5,
        handlingGnd: -0.75,
        handlingWtr: -0.5,
        handlingAir: -0.5,
        handlingGty: -0.75,
        grip: 0.5,
        miniturbo: -0.25
    },
    {
        name: 'Roller',
        speedGnd: -0.5,
        speedWtr: 0,
        speedAir: 0,
        speedGty: -0.5,
        acceleration: 0.5,
        weight: -0.5,
        handlingGnd: 0.25,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: 0.25,
        grip: -0.25,
        miniturbo: 0.75
    },
    {
        name: 'Slim',
        speedGnd: 0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0.5,
        acceleration: -0.5,
        weight: 0,
        handlingGnd: 0.25,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: -1,
        miniturbo: -0.25
    },
    {
        name: 'Slick',
        speedGnd: 0.5,
        speedWtr: -0.75,
        speedAir: -0.75,
        speedGty: 0.5,
        acceleration: -0.75,
        weight: 0.25,
        handlingGnd: -0.25,
        handlingWtr: -0.75,
        handlingAir: -0.5,
        handlingGty: -0.25,
        grip: -1.25,
        miniturbo: -0.75
    },
    {
        name: 'Metal',
        speedGnd: 0.5,
        speedWtr: 0,
        speedAir: -0.25,
        speedGty: -0.25,
        acceleration: -1,
        weight: 0.5,
        handlingGnd: -0.25,
        handlingWtr: -0.25,
        handlingAir: -0.75,
        handlingGty: -0.5,
        grip: -0.75,
        miniturbo: -0.75
    },
    {
        name: 'Button',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0,
        acceleration: 0.25,
        weight: -0.5,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: -0.25,
        handlingGty: 0.25,
        grip: -0.5,
        miniturbo: 0.5
    },
    {
        name: 'Off-Road',
        speedGnd: 0.25,
        speedWtr: 0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -0.25,
        weight: 0.25,
        handlingGnd: -0.5,
        handlingWtr: -0.5,
        handlingAir: -0.25,
        handlingGty: -0.25,
        grip: 0.25,
        miniturbo: -0.5
    },
    {
        name: 'Sponge',
        speedGnd: -0.25,
        speedWtr: -0.5,
        speedAir: 0.25,
        speedGty: -0.25,
        acceleration: 0,
        weight: -0.25,
        handlingGnd: -0.25,
        handlingWtr: -0.5,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: 0.25,
        miniturbo: 0.25
    },
    {
        name: 'Wood',
        speedGnd: 0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0.5,
        acceleration: -0.5,
        weight: 0,
        handlingGnd: 0.25,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: -1,
        miniturbo: -0.25
    },
    {
        name: 'Cushion',
        speedGnd: -0.25,
        speedWtr: -0.5,
        speedAir: 0.25,
        speedGty: -0.25,
        acceleration: 0,
        weight: -0.25,
        handlingGnd: -0.25,
        handlingWtr: -0.5,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: 0.25,
        miniturbo: 0.25
    },
    {
        name: 'Blue Standard',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0
    },
    {
        name: 'Hot Monster',
        speedGnd: 0,
        speedWtr: -0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -0.5,
        weight: 0.5,
        handlingGnd: -0.75,
        handlingWtr: -0.5,
        handlingAir: -0.5,
        handlingGty: -0.75,
        grip: 0.5,
        miniturbo: -0.25
    },
    {
        name: 'Azure Roller',
        speedGnd: -0.5,
        speedWtr: 0,
        speedAir: 0,
        speedGty: -0.5,
        acceleration: 0.5,
        weight: -0.5,
        handlingGnd: 0.25,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: 0.25,
        grip: -0.25,
        miniturbo: 0.75
    },
    {
        name: 'Crimson Slim',
        speedGnd: 0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0.5,
        acceleration: -0.5,
        weight: 0,
        handlingGnd: 0.25,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: -1,
        miniturbo: -0.25
    },
    {
        name: 'Cyber Slick',
        speedGnd: 0.5,
        speedWtr: -0.75,
        speedAir: -0.75,
        speedGty: 0.5,
        acceleration: -0.75,
        weight: 0.25,
        handlingGnd: -0.25,
        handlingWtr: -0.75,
        handlingAir: -0.5,
        handlingGty: -0.25,
        grip: -1.25,
        miniturbo: -0.75
    },
    {
        name: 'Retro Off-Road',
        speedGnd: 0.25,
        speedWtr: 0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -0.25,
        weight: 0.25,
        handlingGnd: -0.5,
        handlingWtr: -0.5,
        handlingAir: -0.25,
        handlingGty: -0.25,
        grip: 0.25,
        miniturbo: -0.5
    },
    {
        name: 'Gold Tires',
        speedGnd: 0.5,
        speedWtr: 0,
        speedAir: -0.25,
        speedGty: -0.25,
        acceleration: -1,
        weight: 0.5,
        handlingGnd: -0.25,
        handlingWtr: -0.25,
        handlingAir: -0.75,
        handlingGty: -0.5,
        grip: -0.75,
        miniturbo: -0.75
    },
    {
        name: 'GLA Tires',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0
    },
    {
        name: 'Triforce Tires',
        speedGnd: 0.25,
        speedWtr: 0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -0.25,
        weight: 0.25,
        handlingGnd: -0.5,
        handlingWtr: -0.5,
        handlingAir: -0.25,
        handlingGty: -0.25,
        grip: 0.25,
        miniturbo: -0.5
    },
    {
        name: 'Ancient Tires',
        speedGnd: 0,
        speedWtr: -0.25,
        speedAir: -0.5,
        speedGty: 0,
        acceleration: -0.5,
        weight: 0.5,
        handlingGnd: -0.75,
        handlingWtr: -0.5,
        handlingAir: -0.5,
        handlingGty: -0.75,
        grip: 0.5,
        miniturbo: -0.25
    },
    {
        name: 'Leaf Tires',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0,
        acceleration: 0.25,
        weight: -0.5,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: -0.25,
        handlingGty: 0.25,
        grip: -0.5,
        miniturbo: 0.5
    }
];

var glider = [
    {
        name: 'Super Glider',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0
    },
    {
        name: 'Cloud Glider',
        speedGnd: -0.25,
        speedWtr: 0,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: -0.25,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0.25
    },
    {
        name: 'Wario Wing',
        speedGnd: 0,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0.25,
        acceleration: 0,
        weight: 0.25,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0
    },
    {
        name: 'Waddle Wing',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0
    },
    {
        name: 'Peach Parasol',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0.25
    },
    {
        name: 'Parachute',
        speedGnd: -0.25,
        speedWtr: 0,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: -0.25,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0.25
    },
    {
        name: 'Parafoil',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0.25
    },
    {
        name: 'Flower Glider',
        speedGnd: -0.25,
        speedWtr: 0,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: -0.25,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0.25
    },
    {
        name: 'Bowser Kite',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0.25
    },
    {
        name: 'Plane Glider',
        speedGnd: 0,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0.25,
        acceleration: 0,
        weight: 0.25,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0
    },
    {
        name: 'MKTV Parafoil',
        speedGnd: -0.25,
        speedWtr: -0.25,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0.25,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0.25
    },
    {
        name: 'Gold Glider',
        speedGnd: 0,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0.25,
        acceleration: 0,
        weight: 0.25,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0
    },
    {
        name: 'Hylian Kite',
        speedGnd: 0,
        speedWtr: 0,
        speedAir: 0,
        speedGty: 0,
        acceleration: 0,
        weight: 0,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0
    },
    {
        name: 'Paraglider',
        speedGnd: 0,
        speedWtr: -0.25,
        speedAir: 0,
        speedGty: 0.25,
        acceleration: 0,
        weight: 0.25,
        handlingGnd: 0,
        handlingWtr: 0.25,
        handlingAir: 0,
        handlingGty: -0.25,
        grip: -0.25,
        miniturbo: 0
    },
    {
        name: 'Paper Glider',
        speedGnd: -0.25,
        speedWtr: 0,
        speedAir: -0.25,
        speedGty: 0.25,
        acceleration: 0.25,
        weight: -0.25,
        handlingGnd: 0,
        handlingWtr: 0,
        handlingAir: 0.25,
        handlingGty: 0,
        grip: 0,
        miniturbo: 0.25
    }
];


const Jtire = JSON.stringify(tire);
fs.writeFileSync('tire.json', Jtire);