var app = app || {};

app.Layout = Backbone.Marionette.Layout.extend({
    el: '#content',
    tagName: 'div',
    regions: {
        'regionDrivers': '#regionDrivers',
        'regionBodies': '#regionBodies',
        'regionTires': '#regionTires',
        'regionGliders': '#regionGliders',
        'regionBuild1': '#regionBuild1',
        'regionBuild2': '#regionBuild2',
        'regionBuild3': '#regionBuild3'
    },
    template: Handlebars.compile($('#main-layout-template').html()),
    onRender: function () {
        var model = new app.Model();

        var myDrivers = [
            new app.MediumDriverModel4({ name: 'Mario', size: 'Medium' }),
            new app.MediumDriverModel3({ name: 'Luigi', size: 'Medium' }),
            new app.MediumDriverModel1({ name: 'Peach', size: 'Medium' }),
            new app.MediumDriverModel1({ name: 'Daisy', size: 'Medium' }),
            new app.HeavyDriverModel0({ name: 'Rosalina', size: 'Large' }),
			new app.MediumDriverModel2({ name: 'Tanooki Mario', size: 'Medium' }),
			new app.MediumDriverModel0({ name: 'Cat Peach', size: 'Medium' }),
            new app.MediumDriverModel1({ name: 'Yoshi', size: 'Medium' }),
            new app.LightDriverModel5({ name: 'Toad', size: 'Small' }),
            new app.LightDriverModel3({ name: 'Koopa Troopa', size: 'Small' }),
            new app.LightDriverModel5({ name: 'Shy Guy', size: 'Small' }),
            new app.LightDriverModel3({ name: 'Lakitu', size: 'Small' }),
            new app.LightDriverModel4({ name: 'Toadette', size: 'Small' }),
			new app.HeavyDriverModel0({ name: 'King Boo', size: 'Large' }),
            new app.LightDriverModel2({ name: 'Baby Mario', size: 'Small' }),
            new app.LightDriverModel2({ name: 'Baby Luigi', size: 'Small' }),
            new app.LightDriverModel0({ name: 'Baby Peach', size: 'Small' }),
            new app.LightDriverModel0({ name: 'Baby Daisy', size: 'Small' }),
            new app.LightDriverModel1({ name: 'Baby Rosalina', size: 'Small' }),
			new app.HeavyDriverModel3({ name: 'Metal Mario', size: 'Medium' }),
            new app.HeavyDriverModel3({ name: 'Pink Gold Peach', size: 'Medium' }),
			new app.HeavyDriverModel2({ name: 'Wario', size: 'Large' }),
            new app.HeavyDriverModel1({ name: 'Waluigi', size: 'Large' }),
			new app.HeavyDriverModel1({ name: 'Donkey Kong', size: 'Large' }),
            new app.HeavyDriverModel4({ name: 'Bowser', size: 'Large' }),
			new app.LightDriverModel2({ name: 'Dry Bones', size: 'Small' }),
			new app.LightDriverModel3({ name: 'Bowser Jr', size: 'Small' }),
			new app.HeavyDriverModel2({ name: 'Dry Bowser', size: 'Large' }),
			new app.LightDriverModel1({ name: 'Lemmy', size: 'Small' }),
			new app.LightDriverModel5({ name: 'Larry', size: 'Small' }),
			new app.LightDriverModel4({ name: 'Wendy', size: 'Small' }),
			new app.MediumDriverModel4({ name: 'Ludwig', size: 'Medium' }),
            new app.MediumDriverModel3({ name: 'Iggy', size: 'Medium' }),
            new app.HeavyDriverModel1({ name: 'Roy', size: 'Large' }),
            new app.HeavyDriverModel4({ name: 'Morton', size: 'Large' }),
			new app.MediumDriverModel0({ name: 'Inkling Girl', size: 'Medium' }),
			new app.MediumDriverModel2({ name: 'Inkling Boy', size: 'Medium' }),
			new app.HeavyDriverModel0({ name: 'Link', size: 'Large' }),
			new app.MediumDriverModel2({ name: 'Villager (male)', size: 'Medium' }),
			new app.MediumDriverModel0({ name: 'Villager (female)', size: 'Medium' }),
			new app.LightDriverModel4({ name: 'Isabelle', size: 'Small' }),
			new app.LightDriverModel2({ name: 'Mii (Light)', size: 'Small' }),
			new app.MediumDriverModel4({ name: 'Mii (Medium)', size: 'Medium' }),
			new app.HeavyDriverModel4({ name: 'Mii (Heavy)', size: 'Large' })

        ];
        var myBodies = new app.BodyCollection([
            new app.BodyModel({
                name: 'Standard Kart'
            }),
            new app.BodyModel({
                name: 'Pipe Frame',
                speedGnd: -0.5,
                speedWtr: 0,
                speedAir: -0.5,
                speedGty: -0.5,
                acceleration: 0.5,
                weight: -0.25,
                handlingGnd: 0.5,
                handlingWtr: 0.5,
                handlingAir: -0.25,
                handlingGty: 0.25,
                grip: 0.25,
                miniturbo: 0.5
            }),
            new app.BodyModel({
                name: 'Mach 8',
                speedGnd: 0,
                speedWtr: 0,
                speedAir: 0.25,
                speedGty: 0.5,
                acceleration: -0.25,
                weight: 0.25,
                handlingGnd: -0.25,
                handlingWtr: 0,
                handlingAir: -0.25,
                handlingGty: 0.25,
                grip: 0.25,
                miniturbo: 0
            }),
            new app.BodyModel({
                name: 'Steel Driver',
                speedGnd: 0.25,
                speedWtr: 0.5,
                speedAir: -0.75,
                speedGty: -0.25,
                acceleration: -0.75,
                weight: 0.5,
                handlingGnd: -0.5,
                handlingWtr: 0.75,
                handlingAir: -0.5,
                handlingGty: -0.5,
                grip: 0,
                miniturbo: -0.5
            }),
            new app.BodyModel({
                name: 'Cat Cruiser',
                speedGnd: -0.25,
                speedWtr: -0.25,
                speedAir: 0.25,
                speedGty: 0,
                acceleration: 0.25,
                weight: 0,
                handlingGnd: 0.25,
                handlingWtr: 0,
                handlingAir: 0.25,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0.25
            }),
            new app.BodyModel({
                name: 'Circuit Special',
                speedGnd: 0.5,
                speedWtr: -0.5,
                speedAir: -0.25,
                speedGty: 0.25,
                acceleration: -0.75,
                weight: 0.25,
                handlingGnd: -0.5,
                handlingWtr: -0.25,
                handlingAir: -0.75,
                handlingGty: -0.25,
                grip: -0.5,
                miniturbo: -0.75
            }),
            new app.BodyModel({
                name: 'Tri-Speeder',
                speedGnd: 0.25,
                speedWtr: 0.5,
                speedAir: -0.75,
                speedGty: -0.25,
                acceleration: -0.75,
                weight: 0.5,
                handlingGnd: -0.5,
                handlingWtr: 0.75,
                handlingAir: -0.5,
                handlingGty: -0.5,
                grip: 0,
                miniturbo: -0.5
            }),
            new app.BodyModel({
                name: 'Badwagon',
                speedGnd: 0.5,
                speedWtr: -0.25,
                speedAir: -0.5,
                speedGty: 0,
                acceleration: -1,
                weight: 0.5,
                handlingGnd: -0.75,
                handlingWtr: -0.25,
                handlingAir: -0.75,
                handlingGty: -0.5,
                grip: 0.5,
                miniturbo: -1
            }),
            new app.BodyModel({
                name: 'Prancer',
                speedGnd: 0.25,
                speedWtr: 0,
                speedAir: 0,
                speedGty: 0,
                acceleration: -0.5,
                weight: -0.25,
                handlingGnd: 0,
                handlingWtr: 0.25,
                handlingAir: 0,
                handlingGty: -0.25,
                grip: -0.25,
                miniturbo: -0.25
            }),
            new app.BodyModel({
                name: 'Biddybuggy',
                speedGnd: -0.75,
                speedWtr: -0.5,
                speedAir: -0.5,
                speedGty: -0.25,
                acceleration: 0.75,
                weight: -0.5,
                handlingGnd: 0.5,
                handlingWtr: 0.5,
                handlingAir: 0.25,
                handlingGty: 0.5,
                grip: 0.25,
                miniturbo: 0.75
            }),
            new app.BodyModel({
                name: 'Landship',
                speedGnd: -0.5,
                speedWtr: 0.5,
                speedAir: -0.25,
                speedGty: -0.75,
                acceleration: 0.5,
                weight: -0.5,
                handlingGnd: 0.25,
                handlingWtr: 0.75,
                handlingAir: 0,
                handlingGty: -0.25,
                grip: 0.75,
                miniturbo: 0.5
            }),
            new app.BodyModel({
                name: 'Sneeker',
                speedGnd: 0.25,
                speedWtr: -0.25,
                speedAir: 0,
                speedGty: 0,
                acceleration: -0.5,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: -0.25,
                handlingGty: 0,
                grip: -0.75,
                miniturbo: -0.25
            }),
            new app.BodyModel({
                name: 'Sports Coupe',
                speedGnd: 0,
                speedWtr: 0,
                speedAir: 0.25,
                speedGty: 0.5,
                acceleration: -0.25,
                weight: 0.25,
                handlingGnd: -0.25,
                handlingWtr: 0,
                handlingAir: -0.25,
                handlingGty: 0.25,
                grip: 0.25,
                miniturbo: 0
            }),
            new app.BodyModel({
                name: 'Gold Standard',
                speedGnd: 0.25,
                speedWtr: -0.25,
                speedAir: 0,
                speedGty: 0,
                acceleration: -0.5,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: -0.25,
                handlingGty: 0,
                grip: -0.75,
                miniturbo: -0.25
            }),
            new app.BodyModel({
                name: 'GLA',
                speedGnd: 0.5,
                speedWtr: -0.25,
                speedAir: -0.5,
                speedGty: 0,
                acceleration: -1,
                weight: 0.5,
                handlingGnd: -0.75,
                handlingWtr: -0.25,
                handlingAir: -0.75,
                handlingGty: -0.5,
                grip: 0.5,
                miniturbo: -1
            }),
            new app.BodyModel({
                name: 'W 25 Silver Arrow',
                speedGnd: -0.25,
                speedWtr: -0.25,
                speedAir: 0,
                speedGty: 0.25,
                acceleration: 0.25,
                weight: -0.25,
                handlingGnd: 0.25,
                handlingWtr: 0.25,
                handlingAir: 0,
                handlingGty: 0.25,
                grip: 0.5,
                miniturbo: 0.25
            }),
            new app.BodyModel({
                name: '300 SL Roadster',
                speedGnd: 0,
                speedWtr: 0,
                speedAir: 0,
                speedGty: 0,
                acceleration: 0,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: 0,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0
            }),
            new app.BodyModel({
                name: 'Blue Falcon',
                speedGnd: 0.25,
                speedWtr: -0.25,
                speedAir: 0,
                speedGty: 0.25,
                acceleration: -0.25,
                weight: -0.5,
                handlingGnd: -0.25,
                handlingWtr: 0.25,
                handlingAir: -0.5,
                handlingGty: 0.5,
                grip: 0,
                miniturbo: -0.25
            }),
            new app.BodyModel({
                name: 'Tanooki Kart',
                speedGnd: -0.25,
                speedWtr: 0.25,
                speedAir: 0,
                speedGty: 0,
                acceleration: -0.5,
                weight: 0.25,
                handlingGnd: 0.25,
                handlingWtr: 0.5,
                handlingAir: 0,
                handlingGty: 0,
                grip: 1,
                miniturbo: -0.25
            }),
            new app.BodyModel({
                name: 'B Dasher',
                speedGnd: 0.5,
                speedWtr: -0.5,
                speedAir: -0.25,
                speedGty: 0.25,
                acceleration: -0.75,
                weight: 0.25,
                handlingGnd: -0.5,
                handlingWtr: -0.25,
                handlingAir: -0.75,
                handlingGty: -0.25,
                grip: -0.5,
                miniturbo: -0.75
            }),
			new app.BodyModel({
				name: 'Streetle',
                speedGnd: -0.5,
                speedWtr: 0.5,
                speedAir: -0.25,
                speedGty: -0.75,
                acceleration: 0.5,
                weight: -0.5,
                handlingGnd: 0.25,
                handlingWtr: 0.75,
                handlingAir: 0,
                handlingGty: -0.25,
                grip: 0.75,
                miniturbo: 0.5
            }),
			new app.BodyModel({
                name: 'P-Wing',
                speedGnd: 0.5,
                speedWtr: -0.5,
                speedAir: -0.25,
                speedGty: 0.25,
                acceleration: -0.75,
                weight: 0.25,
                handlingGnd: -0.5,
                handlingWtr: -0.25,
                handlingAir: -0.75,
                handlingGty: -0.25,
                grip: -0.5,
                miniturbo: -0.75
            }),
			new app.BodyModel({
                name: 'Koopa Clown',
                speedGnd: -0.25,
                speedWtr: 0.25,
                speedAir: 0,
                speedGty: 0,
                acceleration: -0.5,
                weight: 0.25,
                handlingGnd: 0.25,
                handlingWtr: 0.5,
                handlingAir: 0,
                handlingGty: 0,
                grip: 1,
                miniturbo: -0.25
            }),
            new app.BodyModel({
                name: 'Standard Bike',
                speedGnd: -0.25,
                speedWtr: -0.25,
                speedAir: 0,
                speedGty: 0.25,
                acceleration: 0.25,
                weight: -0.25,
                handlingGnd: 0.25,
                handlingWtr: 0.25,
                handlingAir: 0,
                handlingGty: 0.25,
                grip: 0.5,
                miniturbo: 0.25
            }),
            new app.BodyModel({
                name: 'Comet',
                speedGnd: -0.25,
                speedWtr: -0.25,
                speedAir: 0.25,
                speedGty: 0,
                acceleration: 0.25,
                weight: 0,
                handlingGnd: 0.25,
                handlingWtr: 0,
                handlingAir: 0.25,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0.25,
                insideDrift: true
            }),
            new app.BodyModel({
                name: 'Sport Bike',
                speedGnd: 0.25,
                speedWtr: 0,
                speedAir: 0,
                speedGty: 0,
                acceleration: -0.5,
                weight: -0.25,
                handlingGnd: 0,
                handlingWtr: 0.25,
                handlingAir: 0,
                handlingGty: -0.25,
                grip: -0.25,
                miniturbo: -0.25,
                insideDrift: true
            }),
            new app.BodyModel({
                name: 'The Duke',
                speedGnd: 0,
                speedWtr: 0,
                speedAir: 0,
                speedGty: 0,
                acceleration: 0,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: 0,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0
            }),
            new app.BodyModel({
                name: 'Flame Rider',
                speedGnd: -0.25,
                speedWtr: -0.25,
                speedAir: 0,
                speedGty: 0.25,
                acceleration: 0.25,
                weight: -0.25,
                handlingGnd: 0.25,
                handlingWtr: 0.25,
                handlingAir: 0,
                handlingGty: 0.25,
                grip: 0.5,
                miniturbo: 0.25
            }),
            new app.BodyModel({
                name: 'Varmint',
                speedGnd: -0.5,
                speedWtr: 0,
                speedAir: -0.5,
                speedGty: -0.5,
                acceleration: 0.5,
                weight: -0.25,
                handlingGnd: 0.5,
                handlingWtr: 0.5,
                handlingAir: -0.25,
                handlingGty: 0.25,
                grip: 0.25,
                miniturbo: 0.5
            }),
            new app.BodyModel({
                name: 'Mr Scooty',
                speedGnd: -0.75,
                speedWtr: -0.5,
                speedAir: -0.5,
                speedGty: -0.25,
                acceleration: 0.75,
                weight: -0.5,
                handlingGnd: 0.5,
                handlingWtr: 0.5,
                handlingAir: 0.25,
                handlingGty: 0.5,
                grip: 0.25,
                miniturbo: 0.75
            }),
            new app.BodyModel({
                name: 'Jet Bike',
                speedGnd: 0.25,
                speedWtr: 0,
                speedAir: 0,
                speedGty: 0,
                acceleration: -0.5,
                weight: -0.25,
                handlingGnd: 0,
                handlingWtr: 0.25,
                handlingAir: 0,
                handlingGty: -0.25,
                grip: -0.25,
                miniturbo: -0.25,
                insideDrift: true
            }),
            new app.BodyModel({
                name: 'Yoshi Bike',
                speedGnd: -0.25,
                speedWtr: -0.25,
                speedAir: 0.25,
                speedGty: 0,
                acceleration: 0.25,
                weight: 0,
                handlingGnd: 0.25,
                handlingWtr: 0,
                handlingAir: 0.25,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0.25,
                insideDrift: true
            }),
            new app.BodyModel({
                name: 'Master Cycle',
                speedGnd: 0.25,
                speedWtr: -0.25,
                speedAir: 0,
                speedGty: 0,
                acceleration: -0.5,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: -0.25,
                handlingGty: 0,
                grip: -0.75,
                miniturbo: -0.25,
                insideDrift: true
            }),
			new app.BodyModel({
                name: 'Master Cycle Zero',
                speedGnd: -0.25,
                speedWtr: 0.25,
                speedAir: 0,
                speedGty: 0,
                acceleration: -0.5,
                weight: 0.25,
                handlingGnd: 0.25,
                handlingWtr: 0.5,
                handlingAir: 0,
                handlingGty: 0,
                grip: 1,
                miniturbo: -0.25
            }),
			new app.BodyModel({
                name: 'City Tripper',
                speedGnd: -0.5,
                speedWtr: 0,
                speedAir: -0.5,
                speedGty: -0.5,
                acceleration: 0.5,
                weight: -0.25,
                handlingGnd: 0.5,
                handlingWtr: 0.5,
                handlingAir: -0.25,
                handlingGty: 0.25,
                grip: 0.25,
                miniturbo: 0.5
            }),
            new app.BodyModel({
                name: 'Standard ATV',
                speedGnd: 0.5,
                speedWtr: -0.25,
                speedAir: -0.5,
                speedGty: 0,
                acceleration: -1,
                weight: 0.5,
                handlingGnd: -0.75,
                handlingWtr: -0.25,
                handlingAir: -0.75,
                handlingGty: -0.5,
                grip: 0.5,
                miniturbo: -1
            }),
            new app.BodyModel({
                name: 'Wild Wiggler',
                speedGnd: -0.25,
                speedWtr: -0.25,
                speedAir: 0,
                speedGty: 0.25,
                acceleration: 0.25,
                weight: -0.25,
                handlingGnd: 0.25,
                handlingWtr: 0.25,
                handlingAir: 0,
                handlingGty: 0.25,
                grip: 0.5,
                miniturbo: 0.25
            }),
            new app.BodyModel({
                name: 'Teddy Buggy',
                speedGnd: -0.25,
                speedWtr: -0.25,
                speedAir: 0.25,
                speedGty: 0,
                acceleration: 0.25,
                weight: 0,
                handlingGnd: 0.25,
                handlingWtr: 0,
                handlingAir: 0.25,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0.25
            }),
			new app.BodyModel({
                name: 'Bone Rattler',
                speedGnd: 0.25,
                speedWtr: 0.5,
                speedAir: -0.75,
                speedGty: -0.25,
                acceleration: -0.75,
                weight: 0.5,
                handlingGnd: -0.5,
                handlingWtr: 0.75,
                handlingAir: -0.5,
                handlingGty: -0.5,
                grip: 0,
                miniturbo: -0.5
            }),
				new app.BodyModel({
                name: 'Splat Buggy',
                speedGnd: 0.25,
                speedWtr: -0.25,
                speedAir: 0,
                speedGty: 0.25,
                acceleration: -0.25,
                weight: -0.5,
                handlingGnd: -0.25,
                handlingWtr: 0.25,
                handlingAir: -0.5,
                handlingGty: 0.5,
                grip: 0,
                miniturbo: -0.25
            }),
			new app.BodyModel({
                name: 'Inkstriker',
                speedGnd: 0,
                speedWtr: 0,
                speedAir: 0.25,
                speedGty: 0.5,
                acceleration: -0.25,
                weight: 0.25,
                handlingGnd: -0.25,
                handlingWtr: 0,
                handlingAir: -0.25,
                handlingGty: 0.25,
                grip: 0.25,
                miniturbo: 0
            })
        ]);
        var myTires = new app.TireCollection([
            new app.TireModel({
                name: 'Standard',
                speedGnd: 0,
                speedWtr: 0,
                speedAir: 0,
                speedGty: 0,
                acceleration: 0,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: 0,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0
            }),
            new app.TireModel({
                name: 'Monster',
                speedGnd: 0,
                speedWtr: -0.25,
                speedAir: -0.5,
                speedGty: 0,
                acceleration: -0.5,
                weight: 0.5,
                handlingGnd: -0.75,
                handlingWtr: -0.5,
                handlingAir: -0.5,
                handlingGty: -0.75,
                grip: 0.5,
                miniturbo: -0.25
            }),
            new app.TireModel({
                name: 'Roller',
                speedGnd: -0.5,
                speedWtr: 0,
                speedAir: 0,
                speedGty: -0.5,
                acceleration: 0.5,
                weight: -0.5,
                handlingGnd: 0.25,
                handlingWtr: 0.25,
                handlingAir: 0.25,
                handlingGty: 0.25,
                grip: -0.25,
                miniturbo: 0.75
            }),
            new app.TireModel({
                name: 'Slim',
                speedGnd: 0.25,
                speedWtr: -0.25,
                speedAir: -0.25,
                speedGty: 0.5,
                acceleration: -0.5,
                weight: 0,
                handlingGnd: 0.25,
                handlingWtr: 0.25,
                handlingAir: 0.25,
                handlingGty: 0,
                grip: -1,
                miniturbo: -0.25
            }),
            new app.TireModel({
                name: 'Slick',
                speedGnd: 0.5,
                speedWtr: -0.75,
                speedAir: -0.75,
                speedGty: 0.5,
                acceleration: -0.75,
                weight: 0.25,
                handlingGnd: -0.25,
                handlingWtr: -0.75,
                handlingAir: -0.5,
                handlingGty: -0.25,
                grip: -1.25,
                miniturbo: -0.75
            }),
            new app.TireModel({
                name: 'Metal',
                speedGnd: 0.5,
                speedWtr: 0,
                speedAir: -0.25,
                speedGty: -0.25,
                acceleration: -1,
                weight: 0.5,
                handlingGnd: -0.25,
                handlingWtr: -0.25,
                handlingAir: -0.75,
                handlingGty: -0.5,
                grip: -0.75,
                miniturbo: -0.75
            }),
            new app.TireModel({
                name: 'Button',
                speedGnd: -0.25,
                speedWtr: -0.25,
                speedAir: -0.25,
                speedGty: 0,
                acceleration: 0.25,
                weight: -0.5,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: -0.25,
                handlingGty: 0.25,
                grip: -0.5,
                miniturbo: 0.5
            }),
            new app.TireModel({
                name: 'Off-Road',
                speedGnd: 0.25,
                speedWtr: 0.25,
                speedAir: -0.5,
                speedGty: 0,
                acceleration: -0.25,
                weight: 0.25,
                handlingGnd: -0.5,
                handlingWtr: -0.5,
                handlingAir: -0.25,
                handlingGty: -0.25,
                grip: 0.25,
                miniturbo: -0.5
            }),
            new app.TireModel({
                name: 'Sponge',
                speedGnd: -0.25,
                speedWtr: -0.5,
                speedAir: 0.25,
                speedGty: -0.25,
                acceleration: 0,
                weight: -0.25,
                handlingGnd: -0.25,
                handlingWtr: -0.5,
                handlingAir: 0,
                handlingGty: -0.25,
                grip: 0.25,
                miniturbo: 0.25
            }),
            new app.TireModel({
                name: 'Wood',
                speedGnd: 0.25,
                speedWtr: -0.25,
                speedAir: -0.25,
                speedGty: 0.5,
                acceleration: -0.5,
                weight: 0,
                handlingGnd: 0.25,
                handlingWtr: 0.25,
                handlingAir: 0.25,
                handlingGty: 0,
                grip: -1,
                miniturbo: -0.25
            }),
            new app.TireModel({
                name: 'Cushion',
                speedGnd: -0.25,
                speedWtr: -0.5,
                speedAir: 0.25,
                speedGty: -0.25,
                acceleration: 0,
                weight: -0.25,
                handlingGnd: -0.25,
                handlingWtr: -0.5,
                handlingAir: 0,
                handlingGty: -0.25,
                grip: 0.25,
                miniturbo: 0.25
            }),
            new app.TireModel({
                name: 'Blue Standard',
                speedGnd: 0,
                speedWtr: 0,
                speedAir: 0,
                speedGty: 0,
                acceleration: 0,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: 0,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0
            }),
            new app.TireModel({
                name: 'Hot Monster',
                speedGnd: 0,
                speedWtr: -0.25,
                speedAir: -0.5,
                speedGty: 0,
                acceleration: -0.5,
                weight: 0.5,
                handlingGnd: -0.75,
                handlingWtr: -0.5,
                handlingAir: -0.5,
                handlingGty: -0.75,
                grip: 0.5,
                miniturbo: -0.25
            }),
            new app.TireModel({
                name: 'Azure Roller',
                speedGnd: -0.5,
                speedWtr: 0,
                speedAir: 0,
                speedGty: -0.5,
                acceleration: 0.5,
                weight: -0.5,
                handlingGnd: 0.25,
                handlingWtr: 0.25,
                handlingAir: 0.25,
                handlingGty: 0.25,
                grip: -0.25,
                miniturbo: 0.75
            }),
            new app.TireModel({
                name: 'Crimson Slim',
                speedGnd: 0.25,
                speedWtr: -0.25,
                speedAir: -0.25,
                speedGty: 0.5,
                acceleration: -0.5,
                weight: 0,
                handlingGnd: 0.25,
                handlingWtr: 0.25,
                handlingAir: 0.25,
                handlingGty: 0,
                grip: -1,
                miniturbo: -0.25
            }),
            new app.TireModel({
                name: 'Cyber Slick',
                speedGnd: 0.5,
                speedWtr: -0.75,
                speedAir: -0.75,
                speedGty: 0.5,
                acceleration: -0.75,
                weight: 0.25,
                handlingGnd: -0.25,
                handlingWtr: -0.75,
                handlingAir: -0.5,
                handlingGty: -0.25,
                grip: -1.25,
                miniturbo: -0.75
            }),
            new app.TireModel({
                name: 'Retro Off-Road',
                speedGnd: 0.25,
                speedWtr: 0.25,
                speedAir: -0.5,
                speedGty: 0,
                acceleration: -0.25,
                weight: 0.25,
                handlingGnd: -0.5,
                handlingWtr: -0.5,
                handlingAir: -0.25,
                handlingGty: -0.25,
                grip: 0.25,
                miniturbo: -0.5
            }),
            new app.TireModel({
                name: 'Gold Tires',
                speedGnd: 0.5,
                speedWtr: 0,
                speedAir: -0.25,
                speedGty: -0.25,
                acceleration: -1,
                weight: 0.5,
                handlingGnd: -0.25,
                handlingWtr: -0.25,
                handlingAir: -0.75,
                handlingGty: -0.5,
                grip: -0.75,
                miniturbo: -0.75
            }),
            new app.TireModel({
                name: 'GLA Tires',
                speedGnd: 0,
                speedWtr: 0,
                speedAir: 0,
                speedGty: 0,
                acceleration: 0,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: 0,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0
            },
            {
                name: 'Triforce Tires',
                speedGnd: 0.25,
                speedWtr: 0.25,
                speedAir: -0.5,
                speedGty: 0,
                acceleration: -0.25,
                weight: 0.25,
                handlingGnd: -0.5,
                handlingWtr: -0.5,
                handlingAir: -0.25,
                handlingGty: -0.25,
                grip: 0.25,
                miniturbo: -0.5
            },
			{
                name: 'Ancient Tires',
                speedGnd: 0,
                speedWtr: -0.25,
                speedAir: -0.5,
                speedGty: 0,
                acceleration: -0.5,
                weight: 0.5,
                handlingGnd: -0.75,
                handlingWtr: -0.5,
                handlingAir: -0.5,
                handlingGty: -0.75,
                grip: 0.5,
                miniturbo: -0.25
            },
			{
                name: 'Leaf Tires',
                speedGnd: -0.25,
                speedWtr: -0.25,
                speedAir: -0.25,
                speedGty: 0,
                acceleration: 0.25,
                weight: -0.5,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: -0.25,
                handlingGty: 0.25,
                grip: -0.5,
                miniturbo: 0.5
            }
        ];
        var myGliders = [
            {
                name: 'Super Glider',
                speedGnd: 0,
                speedWtr: 0,
                speedAir: 0,
                speedGty: 0,
                acceleration: 0,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: 0,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0
            },
            {
                name: 'Cloud Glider',
                speedGnd: -0.25,
                speedWtr: 0,
                speedAir: -0.25,
                speedGty: 0.25,
                acceleration: 0.25,
                weight: -0.25,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: 0.25,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0.25
            },
            {
                name: 'Wario Wing',
                speedGnd: 0,
                speedWtr: -0.25,
                speedAir: 0,
                speedGty: 0.25,
                acceleration: 0,
                weight: 0.25,
                handlingGnd: 0,
                handlingWtr: 0.25,
                handlingAir: 0,
                handlingGty: -0.25,
                grip: -0.25,
                miniturbo: 0
            },
            {
                name: 'Waddle Wing',
                speedGnd: 0,
                speedWtr: 0,
                speedAir: 0,
                speedGty: 0,
                acceleration: 0,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: 0,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0
            },
            {
                name: 'Peach Parasol',
                speedGnd: -0.25,
                speedWtr: -0.25,
                speedAir: -0.25,
                speedGty: 0.25,
                acceleration: 0.25,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0.25,
                handlingAir: 0.25,
                handlingGty: -0.25,
                grip: -0.25,
                miniturbo: 0.25
            },
            {
                name: 'Parachute',
                speedGnd: -0.25,
                speedWtr: 0,
                speedAir: -0.25,
                speedGty: 0.25,
                acceleration: 0.25,
                weight: -0.25,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: 0.25,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0.25
            },
            {
                name: 'Parafoil',
                speedGnd: -0.25,
                speedWtr: -0.25,
                speedAir: -0.25,
                speedGty: 0.25,
                acceleration: 0.25,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0.25,
                handlingAir: 0.25,
                handlingGty: -0.25,
                grip: -0.25,
                miniturbo: 0.25
            },
            {
                name: 'Flower Glider',
                speedGnd: -0.25,
                speedWtr: 0,
                speedAir: -0.25,
                speedGty: 0.25,
                acceleration: 0.25,
                weight: -0.25,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: 0.25,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0.25
            },
            {
                name: 'Bowser Kite',
                speedGnd: -0.25,
                speedWtr: -0.25,
                speedAir: -0.25,
                speedGty: 0.25,
                acceleration: 0.25,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0.25,
                handlingAir: 0.25,
                handlingGty: -0.25,
                grip: -0.25,
                miniturbo: 0.25
            },
            {
                name: 'Plane Glider',
                speedGnd: 0,
                speedWtr: -0.25,
                speedAir: 0,
                speedGty: 0.25,
                acceleration: 0,
                weight: 0.25,
                handlingGnd: 0,
                handlingWtr: 0.25,
                handlingAir: 0,
                handlingGty: -0.25,
                grip: -0.25,
                miniturbo: 0
            },
            {
                name: 'MKTV Parafoil',
                speedGnd: -0.25,
                speedWtr: -0.25,
                speedAir: -0.25,
                speedGty: 0.25,
                acceleration: 0.25,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0.25,
                handlingAir: 0.25,
                handlingGty: -0.25,
                grip: -0.25,
                miniturbo: 0.25
            },
            {
                name: 'Gold Glider',
                speedGnd: 0,
                speedWtr: -0.25,
                speedAir: 0,
                speedGty: 0.25,
                acceleration: 0,
                weight: 0.25,
                handlingGnd: 0,
                handlingWtr: 0.25,
                handlingAir: 0,
                handlingGty: -0.25,
                grip: -0.25,
                miniturbo: 0
            },
            {
                name: 'Hylian Kite',
                speedGnd: 0,
                speedWtr: 0,
                speedAir: 0,
                speedGty: 0,
                acceleration: 0,
                weight: 0,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: 0,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0
            },
			{
                name: 'Paraglider',
                speedGnd: 0,
                speedWtr: -0.25,
                speedAir: 0,
                speedGty: 0.25,
                acceleration: 0,
                weight: 0.25,
                handlingGnd: 0,
                handlingWtr: 0.25,
                handlingAir: 0,
                handlingGty: -0.25,
                grip: -0.25,
                miniturbo: 0
            },
            {
                name: 'Paper Glider',
                speedGnd: -0.25,
                speedWtr: 0,
                speedAir: -0.25,
                speedGty: 0.25,
                acceleration: 0.25,
                weight: -0.25,
                handlingGnd: 0,
                handlingWtr: 0,
                handlingAir: 0.25,
                handlingGty: 0,
                grip: 0,
                miniturbo: 0.25
            }
        ];
    }
});